spring:
  application:
    name: spring-cloud gateway
  cloud:
    gateway:
      default-filters: #设置默认过滤器
        - AddResponseHeader=source, duck
      routes:
        - id: path_route
          uri: http://localhost:8123 # 断言如果成立，就会重定向到localhost:8123
          predicates:
            - Path=/api/** # 断言为模糊匹配
server:
  port: 8090

#dubbo的配置
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1 # 表示随机分配端口
  registry:
    id: nacos-registry
    address: nacos://localhost:8848?username=nacos&password=nacos

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace